### ISSUE TITLE
Duplicate Navigation Links

### ISSUE THREAD

**Issue by DharamSinghVislavath** [DharamSinghVislavath/pdfEvaluator_#3]
There are redundant navigation links for "Logout," "Dashboard," and "Account" in the provided HTML code, which is a problem. These repetitions could cause the user interface to become redundant and mislead users, which could lead to their clicking on the same link twice or inefficiently reaching their goal 
<img width="468" alt="image" src="https://github.com/DharamSinghVislavath/pdfEvaluator_/assets/145796499/f6a360c8-2f1c-4ece-841d-7315b601128b">

**Comment by VenkataSubhaSriBoddu** [comment]
<img width="465" alt="image" src="https://github.com/DharamSinghVislavath/pdfEvaluator_/assets/145795746/64755080-2d94-41f1-8431-5488ccd2653b">
Symptoms:
Redundant Navigation: The UI (e.g., a site or application) shows a similar route connect at least a few times in a similar area.
Confusion for Users: Clients might be confounded or baffled when they experience copy joins, as it tends to be muddled which one to click.
Aesthetic Issue: It can upset the visual plan and stream of the UI, making it look jumbled and amateurish.
Impact on Program:
User Experience (UX): The presence of copy route connections can debase the general client experience, making disappointment and possibly driving a higher bob rate.
Usability: It decreases the ease of use of the UI as clients might sit around tapping on excess connections.
Aesthetic Quality: It adversely influences the visual allure and amazing skill of the UI.
